# Generated by Django 4.1.7 on 2023-03-29 23:32

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ScaleUp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('about', models.TextField()),
                ('field', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('yt', models.URLField()),
                ('yt_f', models.IntegerField()),
                ('fb', models.URLField()),
                ('fb_f', models.IntegerField()),
                ('insta', models.URLField()),
                ('insta_f', models.IntegerField()),
                ('tt', models.URLField()),
                ('tt_f', models.IntegerField()),
                ('li', models.URLField()),
                ('li_f', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ScaleUp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('status', models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('R', 'Rejected')], max_length=1)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ScaleUp.creator')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ScaleUp.product')),
            ],
        ),
    ]
