# Generated by Django 4.1.7 on 2023-03-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScaleUp', '0002_creator_post_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='fb',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='fb_f',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='insta',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='insta_f',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='li',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='li_f',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='tt',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='tt_f',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='yt',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='yt_f',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='review',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.URLField(null=True),
        ),
    ]
