# Generated by Django 4.1.7 on 2023-03-30 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScaleUp', '0003_alter_creator_fb_alter_creator_fb_f_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='stars',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('R', 'Rejected')], default='Pending', max_length=1),
        ),
    ]
