# Generated by Django 4.1.7 on 2023-03-30 01:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScaleUp', '0004_partner_stars_alter_partner_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='review',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='stars',
        ),
        migrations.AlterField(
            model_name='partner',
            name='status',
            field=models.CharField(choices=[('Pending', 'P'), ('Approved', 'A'), ('Rejected', 'R')], max_length=20),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField(null=True)),
                ('submit', models.CharField(choices=[('Not submitted', 'No'), ('Submitted', 'Yes')], default='Not submitted', max_length=20)),
                ('partner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ScaleUp.partner')),
            ],
        ),
    ]
