# Generated by Django 4.1.7 on 2023-04-19 23:25

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ScaleUp', '0006_alter_review_description_alter_review_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('about', models.TextField()),
                ('field', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('start_date', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('yt', models.URLField()),
                ('yt_f', models.IntegerField()),
                ('fb', models.URLField()),
                ('fb_f', models.IntegerField()),
                ('insta', models.URLField()),
                ('insta_f', models.IntegerField()),
                ('tt', models.URLField()),
                ('tt_f', models.IntegerField()),
                ('li', models.URLField()),
                ('li_f', models.IntegerField()),
            ],
        ),
    ]
