# Generated by Django 4.1.7 on 2023-04-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScaleUp', '0015_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='scaleup/'),
        ),
    ]
