# Generated by Django 4.1.7 on 2023-04-23 10:29

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ScaleUp', '0017_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='fb',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='fb_f',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='field',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='insta',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='insta_f',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='li',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='li_f',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='tt',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='tt_f',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='yt',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='yt_f',
            field=models.IntegerField(null=True),
        ),
    ]
