# Generated by Django 4.1.7 on 2023-04-23 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScaleUp', '0020_creator_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='user',
        ),
    ]
