# Generated by Django 4.1.7 on 2023-04-24 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScaleUp', '0023_alter_creator_about_alter_creator_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ScaleUp.company'),
        ),
    ]
