# Generated by Django 4.1.7 on 2023-05-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScaleUp', '0026_profile_remove_creator_user_delete_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='status',
            field=models.CharField(choices=[('Pending', 'P'), ('Approved', 'A'), ('Rejected', 'R')], max_length=20, null=True),
        ),
    ]
